/* PACSA APPLICATION MANAGEMENT */
let applications=[];
const $=id=>document.getElementById(id);
const normalize=value=>String(value||'').trim().toLowerCase();
const escapeHtml=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const capitalize=value=>{const text=String(value||'');return text.charAt(0).toUpperCase()+text.slice(1)};
function splitFullName(fullName){const parts=String(fullName||'').trim().split(/\s+/).filter(Boolean);if(!parts.length)return{first_name:'',last_name:''};if(parts.length===1)return{first_name:parts[0],last_name:''};return{first_name:parts[0],last_name:parts.slice(1).join(' ')}}
function getStudentDisplayName(student){return [student?.first_name,student?.last_name].filter(Boolean).join(' ').trim()||'Student'}
function formatDate(value){if(!value)return'--';const date=new Date(value);if(Number.isNaN(date.getTime()))return'--';return date.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}
function showError(prefix,error){alert(`${prefix}: ${error?.message||'Unknown error'}`)}

function renderApplications(){const searchText=normalize($('applicationSearch')?.value);const selectedClass=$('classFilter')?.value||'';const selectedStatus=$('statusFilter')?.value||'';const filtered=applications.filter(app=>{const searchable=normalize([app.full_name,app.parent_name,app.email,app.phone,app.class].join(' '));return(!searchText||searchable.includes(searchText))&&(!selectedClass||app.class===selectedClass)&&(!selectedStatus||normalize(app.status||'pending')===normalize(selectedStatus))});const table=$('applicationsTableBody');if(!table)return;table.innerHTML=filtered.map(app=>{const status=normalize(app.status||'pending');return `<tr><td><strong>${escapeHtml(app.full_name||'-')}</strong>${app.email?`<br><small>${escapeHtml(app.email)}</small>`:''}</td><td>${escapeHtml(app.gender||'-')}</td><td>${escapeHtml(app.class||'-')}</td><td>${escapeHtml(app.parent_name||'-')}</td><td>${formatDate(app.created_at)}</td><td><span class="status-badge ${escapeHtml(status)}">${escapeHtml(capitalize(status))}</span></td><td><div style="display:flex;gap:6px;flex-wrap:wrap;"><button type="button" class="btn btn-light" onclick="viewApplication('${app.id}')">View</button>${status==='pending'?`<button type="button" class="btn btn-light" onclick="approveApplication('${app.id}')">Approve</button><button type="button" class="btn btn-light" onclick="rejectApplication('${app.id}')">Reject</button>`:''}<button type="button" class="btn btn-light" onclick="deleteApplication('${app.id}')" style="color:#DC2626;border-color:#FECACA;">Delete</button></div></td></tr>`}).join('');$('emptyApplicationState')&&($('emptyApplicationState').style.display=filtered.length?'none':'block');$('applicationCount')&&($('applicationCount').textContent=filtered.length);$('totalApplications')&&($('totalApplications').textContent=applications.length);$('pendingApplications')&&($('pendingApplications').textContent=applications.filter(app=>normalize(app.status||'pending')==='pending').length);$('approvedApplications')&&($('approvedApplications').textContent=applications.filter(app=>normalize(app.status)==='approved').length);$('rejectedApplications')&&($('rejectedApplications').textContent=applications.filter(app=>normalize(app.status)==='rejected').length)}

async function loadApplications(){const table=$('applicationsTableBody');if(table)table.innerHTML='<tr><td colspan="7">Loading applications...</td></tr>';try{const{data,error}=await supabaseClient.from('applications').select('*').order('created_at',{ascending:false});if(error)throw error;applications=data||[];populateClassFilter();renderApplications()}catch(error){console.error('Load applications error:',error);if(table)table.innerHTML=`<tr><td colspan="7">Could not load applications: ${escapeHtml(error.message)}</td></tr>`}}
function populateClassFilter(){const filter=$('classFilter');if(!filter)return;const currentValue=filter.value;const classes=[...new Set(applications.map(app=>app.class).filter(Boolean))].sort();filter.innerHTML='<option value="">All Classes</option>';classes.forEach(className=>{const option=document.createElement('option');option.value=className;option.textContent=className;filter.appendChild(option)});if(classes.includes(currentValue))filter.value=currentValue}

window.viewApplication=function(id){const app=applications.find(item=>String(item.id)===String(id));if(!app)return;alert(`Applicant: ${app.full_name||'--'}\n\n`+`Date of Birth: ${app.date_of_birth||'--'}\n`+`Gender: ${app.gender||'--'}\n`+`Class: ${app.class||'--'}\n`+`Parent/Guardian: ${app.parent_name||'--'}\n`+`Phone: ${app.phone||'--'}\n`+`Email: ${app.email||'--'}\n`+`NIN: ${app.nin||'--'}\n`+`Birth Certificate: ${app.birth_certificate_path?'Uploaded':'Not uploaded'}\n`+`School Leaving Certificate: ${app.school_leaving_certificate_path?'Uploaded':'Not uploaded'}\n`+`Address: ${app.address||'--'}\n`+`Previous School: ${app.previous_school||'--'}\n`+`Additional Information: ${app.additional_information||'--'}\n\n`+`Status: ${capitalize(app.status||'pending')}`)};

async function generateStudentId(){const{data,error}=await supabaseClient.from('students').select('student_id');if(error)throw error;let highestNumber=0;(data||[]).forEach(student=>{const match=String(student.student_id||'').trim().toUpperCase().match(/^PACSA(\d+)$/);if(match){const number=Number(match[1]);if(Number.isFinite(number)&&number>highestNumber)highestNumber=number}});return 'PACSA'+String(highestNumber+1).padStart(3,'0')}
async function findExistingStudent(app){if(!app.email)return null;const{data,error}=await supabaseClient.from('students').select('student_id,first_name,last_name,email,class,status,portal_status,auth_user_id').ilike('email',app.email.trim()).limit(1);if(error)throw error;return data?.[0]||null}
async function createStudentFromApplication(app){const existing=await findExistingStudent(app);if(existing)return existing;const studentId=await generateStudentId();const names=splitFullName(app.full_name);const studentData={student_id:studentId,first_name:names.first_name,last_name:names.last_name,email:app.email||null,phone:app.phone||null,class:app.class||null,status:'Active',portal_status:'not_activated',auth_user_id:null,nin:app.nin||null,birth_certificate_path:app.birth_certificate_path||null,school_leaving_certificate_path:app.school_leaving_certificate_path||null};const{data,error}=await supabaseClient.from('students').insert([studentData]).select('student_id,first_name,last_name,email,class,status,portal_status,auth_user_id').single();if(error)throw error;return data}
async function createStudentPortalAccess(student){const{data,error}=await supabaseClient.functions.invoke('create-portal-user',{body:{role:'student',record_id:student.student_id,email:student.email}});if(error)throw error;if(data&&!data.ok)throw new Error(data.error||'Could not create Student Portal access.');return data||null}
async function sendAdmissionEmail(app,student,portalAccess){const{error}=await supabaseClient.functions.invoke('smooth-api',{body:{application_id:app.id,full_name:app.full_name,email:app.email,class:app.class,student_id:student.student_id,portal_status:'active',temporary_password:portalAccess?.temporary_password||'',temporary_password_expires_at:portalAccess?.temporary_password_expires_at||'',login_url:portalAccess?.login_url||''}});if(error)throw error;return true}

window.approveApplication=async function(id){const app=applications.find(item=>String(item.id)===String(id));if(!app)return;const confirmed=confirm(`Approve ${app.full_name}'s application?\n\nA student record, portal account and temporary password will be created.`);if(!confirmed)return;try{const{data:freshApp,error:freshError}=await supabaseClient.from('applications').select('*').eq('id',id).maybeSingle();if(freshError)throw freshError;if(!freshApp)throw new Error('This application no longer exists.');if(normalize(freshApp.status||'pending')!=='pending'){alert(`This application is already ${freshApp.status}.`);await loadApplications();return}if(!freshApp.email){alert('This applicant has no email address. Student Portal access requires an email.');return}const student=await createStudentFromApplication(freshApp);const portalAccess=await createStudentPortalAccess(student);const{data:updatedApplication,error:approvalError}=await supabaseClient.from('applications').update({status:'approved'}).eq('id',id).eq('status',freshApp.status).select();if(approvalError)throw approvalError;if(!updatedApplication||updatedApplication.length!==1){alert('The application changed before approval completed.');await loadApplications();return}await loadApplications();let admissionEmailSent=false;try{admissionEmailSent=await sendAdmissionEmail(freshApp,student,portalAccess)}catch(emailError){console.error('Admission email error:',emailError)}const studentName=getStudentDisplayName(student);alert(`Application approved successfully!\n\nStudent: ${studentName}\nStudent ID: ${student.student_id}\nClass: ${student.class||freshApp.class||'--'}\nTemporary Password: ${portalAccess?.temporary_password||'Created'}\nExpires: ${portalAccess?.temporary_password_expires_at?new Date(portalAccess.temporary_password_expires_at).toLocaleString():'24 hours'}\n\n${portalAccess?.email_sent?'Portal access email sent.':'Portal password created, but portal email may need manual sharing.'}\n${admissionEmailSent?'Admission email sent.':'Admission email could not be sent.'}`)}catch(error){console.error('Approve application error:',error);showError('Could not approve application',error)}};

window.rejectApplication=async function(id){const app=applications.find(item=>String(item.id)===String(id));if(!app)return;if(!confirm(`Reject ${app.full_name}'s application?`))return;try{const{data,error}=await supabaseClient.from('applications').update({status:'rejected'}).eq('id',id).eq('status',app.status||'pending').select();if(error)throw error;if(!data||data.length!==1){alert('This application has already been changed.');await loadApplications();return}await loadApplications();alert('Application rejected successfully.')}catch(error){console.error('Reject application error:',error);showError('Could not reject application',error)}};
window.deleteApplication=async function(id){const app=applications.find(item=>String(item.id)===String(id));if(!app)return;let message=`Delete ${app.full_name}'s application?`;if(normalize(app.status||'pending')==='approved')message+='\n\nThis application was already approved.\nThe student record will NOT be deleted.';if(!confirm(message))return;if(!confirm('This application record will be permanently deleted.\n\nContinue?'))return;try{const{error}=await supabaseClient.from('applications').delete().eq('id',id);if(error)throw error;await loadApplications();alert('Application deleted successfully.')}catch(error){console.error('Delete application error:',error);showError('Could not delete application',error)}};
function clearFilters(){if($('applicationSearch'))$('applicationSearch').value='';if($('classFilter'))$('classFilter').value='';if($('statusFilter'))$('statusFilter').value='';renderApplications()}
document.addEventListener('DOMContentLoaded',async()=>{const admin=await window.adminAuthReady;if(!admin)return;$('applicationSearch')?.addEventListener('input',renderApplications);$('classFilter')?.addEventListener('change',renderApplications);$('statusFilter')?.addEventListener('change',renderApplications);$('clearFiltersBtn')?.addEventListener('click',clearFilters);$('menuBtn')?.addEventListener('click',()=>{$('sidebar')?.classList.toggle('active')});await loadApplications()});
