/* PACSA TEACHERS MANAGEMENT */
let teachers=[];
let teacherAssignments=[];
let classTeacherAssignments=[];
const $=id=>document.getElementById(id);
const clean=v=>String(v??'').trim();
const norm=v=>clean(v).toLowerCase();
const escapeHtml=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const escapeAttribute=escapeHtml;
function getTeacherName(t){return `${t?.first_name||''} ${t?.last_name||''}`.trim()||t?.teacher_id||'Teacher'}
function getInitials(name){return clean(name).split(/\s+/).filter(Boolean).slice(0,2).map(w=>w[0]).join('').toUpperCase()||'T'}

async function loadTeachers(){if($('teachersLoading'))$('teachersLoading').style.display='block';if($('emptyTeacherState'))$('emptyTeacherState').style.display='none';try{const{data,error}=await supabaseClient.from('Teachers').select('id,teacher_id,first_name,last_name,email,phone,class,subject,auth_user_id,portal_status').order('first_name',{ascending:true});if(error)throw error;teachers=data||[];await Promise.all([loadTeacherAssignments(),loadClassTeacherAssignments()]);populateClasses();renderTeachers();updateStatistics()}catch(error){console.error('Could not load teachers:',error);alert('Could not load teachers: '+error.message)}finally{if($('teachersLoading'))$('teachersLoading').style.display='none'}}
async function loadTeacherAssignments(){const{data,error}=await supabaseClient.from('teacher_assignments').select('id,teacher_id,class,subject,created_at').order('created_at',{ascending:true});if(error){console.error('Could not load teacher assignments:',error);teacherAssignments=[];return}teacherAssignments=data||[]}
async function loadClassTeacherAssignments(){const{data,error}=await supabaseClient.from('class_teacher_assignments').select('id,teacher_id,class,session');if(error){console.error('Could not load class teacher assignments:',error);classTeacherAssignments=[];return}classTeacherAssignments=data||[]}
function getTeacherAssignments(teacherId){return teacherAssignments.filter(a=>String(a.teacher_id)===String(teacherId))}
function getClassTeacherAssignments(teacherId){return classTeacherAssignments.filter(a=>String(a.teacher_id)===String(teacherId))}

function renderTeachers(){const search=norm($('teacherSearch')?.value);const selectedClass=$('departmentFilter')?.value||'';const filtered=teachers.filter(t=>{const assignments=getTeacherAssignments(t.teacher_id);const assignmentClasses=assignments.map(a=>a.class).filter(Boolean);const matchesClass=!selectedClass||t.class===selectedClass||assignmentClasses.includes(selectedClass);const matchesSearch=!search||norm([getTeacherName(t),t.teacher_id,t.email].join(' ')).includes(search);return matchesClass&&matchesSearch});if($('teachersTableBody')){$('teachersTableBody').innerHTML=filtered.map(t=>{const name=getTeacherName(t);const assignments=getTeacherAssignments(t.teacher_id);let classHtml='',subjectHtml='';if(assignments.length){classHtml=[...new Set(assignments.map(a=>a.class).filter(Boolean))].map(c=>`<span class="assignment-badge">${escapeHtml(c)}</span>`).join('');subjectHtml=[...new Set(assignments.map(a=>a.subject).filter(Boolean))].map(s=>`<span class="assignment-badge">${escapeHtml(s)}</span>`).join('')}else{classHtml=t.class?`<span class="assignment-badge">${escapeHtml(t.class)}</span>`:'<span class="no-assignment">Not assigned</span>';subjectHtml=t.subject?`<span class="assignment-badge">${escapeHtml(t.subject)}</span>`:'<span class="no-assignment">Not assigned</span>'}return `<tr><td><div class="teacher-cell"><div class="teacher-table-avatar">${escapeHtml(getInitials(name))}</div><div class="teacher-name-info"><strong>${escapeHtml(name)}</strong><span>${escapeHtml(t.email||'-')}</span></div></div></td><td>${escapeHtml(t.teacher_id||'-')}</td><td><div class="assignment-summary">${classHtml}</div></td><td><div class="assignment-summary">${subjectHtml}</div></td><td>${escapeHtml(t.phone||'-')}</td><td><div class="table-action-buttons"><button type="button" class="table-btn view-table-btn" onclick="viewTeacher('${t.id}')" title="View Teacher">👁</button><button type="button" class="table-btn edit-table-btn" onclick="editTeacher('${t.id}')" title="Edit Teacher">✏</button><button type="button" class="table-btn delete-table-btn" onclick="deleteTeacher('${t.id}')" title="Delete Teacher">🗑</button></div></td></tr>`}).join('')}if($('emptyTeacherState'))$('emptyTeacherState').style.display=filtered.length?'none':'block';if($('teacherCount'))$('teacherCount').textContent=filtered.length}
function populateClasses(){const filter=$('departmentFilter');if(!filter)return;const oldValue=filter.value;const unique=[...new Set([...teachers.map(t=>t.class),...teacherAssignments.map(a=>a.class)].filter(Boolean))].sort();filter.innerHTML='<option value="">All Classes</option>';unique.forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;filter.appendChild(o)});if(unique.includes(oldValue))filter.value=oldValue}
function updateStatistics(){if($('totalTeachers'))$('totalTeachers').textContent=teachers.length;if($('activeTeachers'))$('activeTeachers').textContent=teachers.filter(t=>norm(t.portal_status||'active')!=='inactive').length;if($('totalDepartments'))$('totalDepartments').textContent=[...new Set(teacherAssignments.map(a=>a.class).filter(Boolean))].length;if($('classTeachers'))$('classTeachers').textContent=[...new Set(classTeacherAssignments.map(a=>a.teacher_id).filter(Boolean))].length;if($('teacherCount'))$('teacherCount').textContent=teachers.length}

function openTeacherModal(teacher=null){$('teacherForm')?.reset();if($('teacherRecordId'))$('teacherRecordId').value=teacher?.id||'';if($('teacherModalTitle'))$('teacherModalTitle').textContent=teacher?'Edit Teacher':'Add New Teacher';if($('teacherFirstName'))$('teacherFirstName').value=teacher?.first_name||'';if($('teacherLastName'))$('teacherLastName').value=teacher?.last_name||'';if($('teacherId'))$('teacherId').value=teacher?.teacher_id||'';if($('teacherEmail'))$('teacherEmail').value=teacher?.email||'';if($('teacherPhone'))$('teacherPhone').value=teacher?.phone||'';if($('assignmentList'))$('assignmentList').innerHTML='';if(teacher){const assignments=getTeacherAssignments(teacher.teacher_id);(assignments.length?assignments:[{class:teacher.class||'',subject:teacher.subject||''}]).forEach(a=>addAssignmentRow(a.class,a.subject))}else{addAssignmentRow()}$('teacherModal')?.classList.add('active')}
function addAssignmentRow(className='',subject=''){const container=$('assignmentList');if(!container)return;const row=document.createElement('div');row.className='assignment-row';row.innerHTML=`<div class="form-group"><label>Class</label><input type="text" class="assignment-class" placeholder="e.g. SS2" value="${escapeAttribute(className)}" required></div><div class="form-group"><label>Subject</label><input type="text" class="assignment-subject" placeholder="e.g. Mathematics" value="${escapeAttribute(subject)}" required></div><button type="button" class="remove-assignment-btn" title="Remove Assignment">🗑</button>`;row.querySelector('.remove-assignment-btn')?.addEventListener('click',()=>{const rows=$('assignmentList')?.querySelectorAll('.assignment-row');if(rows&&rows.length<=1){alert('A teacher must have at least one teaching assignment.');return}row.remove()});container.appendChild(row)}
function getAssignmentsFromForm(){const rows=$('assignmentList')?.querySelectorAll('.assignment-row')||[];const list=[];rows.forEach(row=>{const className=clean(row.querySelector('.assignment-class')?.value);const subject=clean(row.querySelector('.assignment-subject')?.value);if(className&&subject)list.push({class:className,subject})});const seen=new Set();return list.filter(a=>{const key=`${norm(a.class)}|${norm(a.subject)}`;if(seen.has(key))return false;seen.add(key);return true})}
function closeTeacherModal(){$('teacherModal')?.classList.remove('active')}
function closeViewTeacherModal(){$('viewTeacherModal')?.classList.remove('active')}

async function createTeacherPortalAccess(teacherData){const{data,error}=await supabaseClient.functions.invoke('create-portal-user',{body:{role:'teacher',record_id:teacherData.teacher_id,email:teacherData.email}});if(error)throw error;if(data&&!data.ok)throw new Error(data.error||'Could not create Teacher Portal access.');return data||null}
async function saveTeacher(event){event.preventDefault();const recordId=$('teacherRecordId')?.value||'';const existingTeacher=recordId?teachers.find(t=>String(t.id)===String(recordId)):null;const oldTeacherId=existingTeacher?.teacher_id||'';const teacherData={first_name:clean($('teacherFirstName')?.value),last_name:clean($('teacherLastName')?.value),teacher_id:clean($('teacherId')?.value),email:clean($('teacherEmail')?.value).toLowerCase(),phone:clean($('teacherPhone')?.value)};if(!teacherData.first_name||!teacherData.last_name||!teacherData.teacher_id||!teacherData.email){alert('Please enter First Name, Last Name, Teacher ID and Email.');return}const assignments=getAssignmentsFromForm();if(!assignments.length){alert('Please add at least one valid class and subject assignment.');return}teacherData.class=assignments[0].class;teacherData.subject=assignments[0].subject;const button=$('saveTeacherBtn');if(button){button.disabled=true;button.textContent='Saving...'}try{const duplicate=teachers.find(t=>norm(t.teacher_id)===norm(teacherData.teacher_id)&&String(t.id)!==String(recordId));if(duplicate)throw new Error('Another teacher already uses this Teacher ID.');if(recordId){const{error}=await supabaseClient.from('Teachers').update(teacherData).eq('id',recordId);if(error)throw error;if(oldTeacherId&&oldTeacherId!==teacherData.teacher_id){const{error:classTeacherUpdateError}=await supabaseClient.from('class_teacher_assignments').update({teacher_id:teacherData.teacher_id}).eq('teacher_id',oldTeacherId);if(classTeacherUpdateError)throw classTeacherUpdateError}const{error:deleteError}=await supabaseClient.from('teacher_assignments').delete().eq('teacher_id',oldTeacherId||teacherData.teacher_id);if(deleteError)throw deleteError}else{const{error}=await supabaseClient.from('Teachers').insert([teacherData]);if(error)throw error}const assignmentRows=assignments.map(a=>({teacher_id:teacherData.teacher_id,class:a.class,subject:a.subject}));const{error:assignmentError}=await supabaseClient.from('teacher_assignments').insert(assignmentRows);if(assignmentError)throw assignmentError;let portal=null;if(!recordId){if(button)button.textContent='Creating portal access...';portal=await createTeacherPortalAccess(teacherData)}closeTeacherModal();await loadTeachers();alert(recordId?'Teacher and assignments updated successfully.':`Teacher and assignments added successfully.\n\nTeacher ID: ${teacherData.teacher_id}\nEmail: ${teacherData.email}\nTemporary Password: ${portal?.temporary_password||'Created'}\nExpires: ${portal?.temporary_password_expires_at?new Date(portal.temporary_password_expires_at).toLocaleString():'24 hours'}\n\n${portal?.email_sent?'Portal details were emailed to the teacher.':'Portal access was created, but email may need manual sharing.'}`)}catch(error){console.error('Save teacher error:',error);alert('Could not save teacher: '+(error?.message||'Unknown error'))}finally{if(button){button.disabled=false;button.textContent='Save Teacher'}}}

window.viewTeacher=function(id){const teacher=teachers.find(t=>String(t.id)===String(id));if(!teacher)return;const name=getTeacherName(teacher);if($('viewTeacherAvatar'))$('viewTeacherAvatar').textContent=getInitials(name);if($('viewTeacherName'))$('viewTeacherName').textContent=name;if($('viewTeacherId'))$('viewTeacherId').textContent=teacher.teacher_id||'-';if($('viewTeacherEmail'))$('viewTeacherEmail').textContent=teacher.email||'-';if($('viewTeacherPhone'))$('viewTeacherPhone').textContent=teacher.phone||'-';const assignments=getTeacherAssignments(teacher.teacher_id);const classTeacherRoles=getClassTeacherAssignments(teacher.teacher_id);const container=$('viewTeacherAssignments');if(container){const teachingHtml=assignments.map(a=>`<span class="assignment-badge">🏫 ${escapeHtml(a.class)} — 📚 ${escapeHtml(a.subject)}</span>`);const classTeacherHtml=classTeacherRoles.map(a=>`<span class="assignment-badge">👨‍🏫 Class Teacher: ${escapeHtml(a.class)}${a.session?` — ${escapeHtml(a.session)}`:''}</span>`);container.innerHTML=[...teachingHtml,...classTeacherHtml].join('')||'<span class="no-assignment">No teaching assignments found.</span>'}if($('viewTeacherDepartment'))$('viewTeacherDepartment').textContent=[...new Set(assignments.map(a=>a.class).filter(Boolean))].join(', ')||teacher.class||'-';$('viewTeacherModal')?.classList.add('active')};
window.editTeacher=function(id){const teacher=teachers.find(t=>String(t.id)===String(id));if(teacher)openTeacherModal(teacher)};
window.deleteTeacher=async function(id){const teacher=teachers.find(t=>String(t.id)===String(id));if(!teacher)return;const name=getTeacherName(teacher);if(!confirm(`Are you sure you want to delete ${name}?`))return;try{const{error:assignmentDeleteError}=await supabaseClient.from('teacher_assignments').delete().eq('teacher_id',teacher.teacher_id);if(assignmentDeleteError)throw assignmentDeleteError;const{error:classTeacherDeleteError}=await supabaseClient.from('class_teacher_assignments').delete().eq('teacher_id',teacher.teacher_id);if(classTeacherDeleteError)throw classTeacherDeleteError;const{error:teacherDeleteError}=await supabaseClient.from('Teachers').delete().eq('id',id);if(teacherDeleteError)throw teacherDeleteError;await loadTeachers();alert('Teacher and all assignments deleted successfully.')}catch(error){console.error('Delete teacher error:',error);alert('Could not delete teacher: '+error.message)}};

document.addEventListener('DOMContentLoaded',async()=>{const admin=await window.adminAuthReady;if(!admin)return;$('menuBtn')?.addEventListener('click',()=>{$('sidebar')?.classList.toggle('active')});$('teacherSearch')?.addEventListener('input',renderTeachers);$('departmentFilter')?.addEventListener('change',renderTeachers);$('clearFiltersBtn')?.addEventListener('click',()=>{if($('teacherSearch'))$('teacherSearch').value='';if($('departmentFilter'))$('departmentFilter').value='';renderTeachers()});$('addTeacherBtn')?.addEventListener('click',()=>openTeacherModal());$('emptyAddTeacherBtn')?.addEventListener('click',()=>openTeacherModal());$('addAssignmentBtn')?.addEventListener('click',()=>addAssignmentRow());$('closeTeacherModal')?.addEventListener('click',closeTeacherModal);$('cancelTeacherBtn')?.addEventListener('click',closeTeacherModal);$('closeViewTeacherModal')?.addEventListener('click',closeViewTeacherModal);$('teacherModal')?.addEventListener('click',e=>{if(e.target===$('teacherModal'))closeTeacherModal()});$('viewTeacherModal')?.addEventListener('click',e=>{if(e.target===$('viewTeacherModal'))closeViewTeacherModal()});$('teacherForm')?.addEventListener('submit',saveTeacher);await loadTeachers()});
