-- PACSA role + assessment workflow reconstruction
-- 2026-09-16

begin;

-- ADMIN ROLES
alter table if exists public.admins
  add column if not exists role text not null default 'admin';

update public.admins
set role = 'super_admin'
where id = (
  select id
  from public.admins
  where lower(coalesce(status,'active')) = 'active'
  order by id
  limit 1
);

alter table if exists public.admins
  drop constraint if exists admins_role_check;

alter table if exists public.admins
  add constraint admins_role_check
  check (role in ('super_admin','admin'));

-- TEACHER / PRINCIPAL ROLES
alter table if exists public."Teachers"
  add column if not exists role text not null default 'teacher';

alter table if exists public."Teachers"
  drop constraint if exists teachers_role_check;

alter table if exists public."Teachers"
  add constraint teachers_role_check
  check (role in ('teacher','principal'));

-- A principal may teach subjects, but must not be a class teacher.
create or replace function public.pacsa_block_principal_class_teacher()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if exists (
    select 1
    from public."Teachers" t
    where t.teacher_id = new.teacher_id
      and lower(coalesce(t.role,'teacher')) = 'principal'
  ) then
    raise exception 'A principal cannot be assigned as a class teacher.';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_pacsa_block_principal_class_teacher on public.class_teacher_assignments;
create trigger trg_pacsa_block_principal_class_teacher
before insert or update on public.class_teacher_assignments
for each row execute function public.pacsa_block_principal_class_teacher();

-- ASSESSMENT CONTROL
create table if not exists public.assessment_periods (
  id bigint generated by default as identity primary key,
  session text not null,
  term text not null,
  current_stage text not null default 'ca',
  ca_open boolean not null default true,
  exam_open boolean not null default false,
  updated_at timestamptz not null default now(),
  unique(session, term),
  constraint assessment_periods_stage_check check (current_stage in ('ca','exam','closed'))
);

alter table public.assessment_periods enable row level security;

-- Result structure: First CA /10 + Second CA /20 = CA /30; Exam /70; Total /100.
alter table if exists public.results
  add column if not exists first_ca numeric(5,2),
  add column if not exists second_ca numeric(5,2),
  add column if not exists ca_status text not null default 'draft',
  add column if not exists ca_published_at timestamptz,
  add column if not exists assessment_stage text not null default 'ca';

alter table if exists public.results
  drop constraint if exists results_first_ca_check;
alter table if exists public.results
  add constraint results_first_ca_check
  check (first_ca is null or (first_ca >= 0 and first_ca <= 10));

alter table if exists public.results
  drop constraint if exists results_second_ca_check;
alter table if exists public.results
  add constraint results_second_ca_check
  check (second_ca is null or (second_ca >= 0 and second_ca <= 20));

alter table if exists public.results
  drop constraint if exists results_ca_30_check;
alter table if exists public.results
  add constraint results_ca_30_check
  check (ca is null or (ca >= 0 and ca <= 30));

alter table if exists public.results
  drop constraint if exists results_exam_70_check;
alter table if exists public.results
  add constraint results_exam_70_check
  check (exam is null or (exam >= 0 and exam <= 70));

alter table if exists public.results
  drop constraint if exists results_total_100_check;
alter table if exists public.results
  add constraint results_total_100_check
  check (total is null or (total >= 0 and total <= 100));

alter table if exists public.results
  drop constraint if exists results_ca_status_check;
alter table if exists public.results
  add constraint results_ca_status_check
  check (ca_status in ('draft','published'));

alter table if exists public.results
  drop constraint if exists results_assessment_stage_check;
alter table if exists public.results
  add constraint results_assessment_stage_check
  check (assessment_stage in ('ca','exam'));

-- Keep CA and total consistent even if a client sends an incorrect total.
create or replace function public.pacsa_normalize_result_scores()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.first_ca is not null or new.second_ca is not null then
    new.ca := coalesce(new.first_ca,0) + coalesce(new.second_ca,0);
  end if;

  if new.assessment_stage = 'ca' then
    new.total := new.ca;
  else
    new.total := coalesce(new.ca,0) + coalesce(new.exam,0);
  end if;

  return new;
end;
$$;

drop trigger if exists trg_pacsa_normalize_result_scores on public.results;
create trigger trg_pacsa_normalize_result_scores
before insert or update on public.results
for each row execute function public.pacsa_normalize_result_scores();

-- REPORT REMARKS
alter table if exists public.student_reports
  add column if not exists teacher_remark text,
  add column if not exists principal_remark text,
  add column if not exists principal_teacher_id text,
  add column if not exists principal_reviewed_at timestamptz;

-- Preserve existing class-teacher remarks.
update public.student_reports
set teacher_remark = remark
where teacher_remark is null
  and nullif(trim(coalesce(remark,'')),'') is not null;

-- Class teacher's legacy remark field remains supported and mirrors teacher_remark.
create or replace function public.pacsa_sync_teacher_remark()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.teacher_remark is null and new.remark is not null then
    new.teacher_remark := new.remark;
  elsif new.remark is null and new.teacher_remark is not null then
    new.remark := new.teacher_remark;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_pacsa_sync_teacher_remark on public.student_reports;
create trigger trg_pacsa_sync_teacher_remark
before insert or update on public.student_reports
for each row execute function public.pacsa_sync_teacher_remark();

-- Useful role helpers for authenticated clients.
create or replace function public.pacsa_get_my_admin_role()
returns text
language sql
security definer
set search_path = public
as $$
  select a.role
  from public.admins a
  where a.auth_user_id = auth.uid()
    and lower(coalesce(a.status,'active')) = 'active'
  limit 1;
$$;

create or replace function public.pacsa_get_my_teacher_role()
returns text
language sql
security definer
set search_path = public
as $$
  select t.role
  from public."Teachers" t
  where t.auth_user_id = auth.uid()
    and lower(coalesce(t.portal_status,'active')) = 'active'
  limit 1;
$$;

grant execute on function public.pacsa_get_my_admin_role() to authenticated;
grant execute on function public.pacsa_get_my_teacher_role() to authenticated;

commit;
