-- PACSA security additions: audit log + class-teacher notifications
-- Run once in Supabase SQL Editor.

begin;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid,
  actor_role text,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_created_at_idx on public.audit_logs(created_at desc);
create index if not exists audit_logs_entity_idx on public.audit_logs(entity_type, entity_id);

alter table public.audit_logs enable row level security;
revoke all on public.audit_logs from anon, authenticated;
grant select on public.audit_logs to authenticated;

drop policy if exists "Super Admin can read audit logs" on public.audit_logs;
create policy "Super Admin can read audit logs"
on public.audit_logs for select
to authenticated
using (
  exists (
    select 1 from public.admins a
    where a.auth_user_id = auth.uid()
      and a.role = 'super_admin'
      and lower(coalesce(a.status,'active')) = 'active'
  )
);

create table if not exists public.teacher_notifications (
  id bigint generated by default as identity primary key,
  teacher_id text not null,
  type text not null default 'result_added',
  title text not null,
  message text not null,
  student_id text,
  class text,
  subject text,
  term text,
  session text,
  result_id text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists teacher_notifications_teacher_idx
  on public.teacher_notifications(teacher_id, is_read, created_at desc);

alter table public.teacher_notifications enable row level security;
revoke all on public.teacher_notifications from anon, authenticated;

create or replace function public.pacsa_actor_role()
returns text
language sql
security definer
set search_path = public
as $$
  select coalesce(
    (select case when a.role='super_admin' then 'super_admin' else 'admin' end
       from public.admins a
      where a.auth_user_id=auth.uid() and lower(coalesce(a.status,'active'))='active'
      limit 1),
    (select coalesce(t.role,'teacher')
       from public."Teachers" t
      where t.auth_user_id=auth.uid() and lower(coalesce(t.portal_status,'active'))='active'
      limit 1),
    (select 'student'
       from public.students s
      where s.auth_user_id=auth.uid()
      limit 1),
    'system'
  );
$$;

create or replace function public.pacsa_audit_row_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  entity_value text;
  action_value text;
  details_value jsonb;
begin
  action_value := lower(tg_op);

  if tg_table_name = 'results' then
    entity_value := coalesce((case when tg_op='DELETE' then old.id else new.id end)::text,'');
  elsif tg_table_name = 'student_reports' then
    entity_value := coalesce(case when tg_op='DELETE' then old.student_id else new.student_id end,'');
  elsif tg_table_name = 'students' then
    entity_value := coalesce(case when tg_op='DELETE' then old.student_id else new.student_id end,'');
  elsif tg_table_name = 'Teachers' then
    entity_value := coalesce(case when tg_op='DELETE' then old.teacher_id else new.teacher_id end,'');
  elsif tg_table_name = 'applications' then
    entity_value := coalesce((case when tg_op='DELETE' then old.id else new.id end)::text,'');
  elsif tg_table_name = 'assessment_periods' then
    entity_value := coalesce(case when tg_op='DELETE' then old.session||'/'||old.term else new.session||'/'||new.term end,'');
  elsif tg_table_name = 'teacher_assignments' or tg_table_name = 'class_teacher_assignments' then
    entity_value := coalesce((case when tg_op='DELETE' then old.id else new.id end)::text,'');
  else
    entity_value := '';
  end if;

  details_value := jsonb_build_object('operation', tg_op, 'table', tg_table_name);

  insert into public.audit_logs(actor_user_id,actor_role,action,entity_type,entity_id,details)
  values(auth.uid(),public.pacsa_actor_role(),action_value,tg_table_name,entity_value,details_value);

  return case when tg_op='DELETE' then old else new end;
end;
$$;

do $$
declare table_name text;
begin
  foreach table_name in array array['results','student_reports','students','Teachers','applications','assessment_periods','teacher_assignments','class_teacher_assignments']
  loop
    if to_regclass(format('public.%I',table_name)) is not null then
      execute format('drop trigger if exists pacsa_audit_%I on public.%I',table_name,table_name);
      execute format('create trigger pacsa_audit_%I after insert or update or delete on public.%I for each row execute function public.pacsa_audit_row_change()',table_name,table_name);
    end if;
  end loop;
end $$;

create or replace function public.pacsa_notify_class_teacher_result()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  class_teacher_id text;
  actor_teacher_id text;
  should_notify boolean := false;
begin
  select t.teacher_id into actor_teacher_id
  from public."Teachers" t
  where t.auth_user_id=auth.uid()
  limit 1;

  if tg_op='INSERT' then
    should_notify := true;
  else
    should_notify :=
      new.first_ca is distinct from old.first_ca or
      new.second_ca is distinct from old.second_ca or
      new.ca is distinct from old.ca or
      new.exam is distinct from old.exam or
      new.total is distinct from old.total or
      new.status is distinct from old.status;
  end if;

  if not should_notify then return new; end if;

  select c.teacher_id into class_teacher_id
  from public.class_teacher_assignments c
  where lower(trim(c.class))=lower(trim(new.class))
    and lower(trim(c.session))=lower(trim(new.session))
  order by c.id desc
  limit 1;

  if class_teacher_id is null or class_teacher_id = actor_teacher_id then
    return new;
  end if;

  insert into public.teacher_notifications(
    teacher_id,type,title,message,student_id,class,subject,term,session,result_id
  ) values (
    class_teacher_id,
    'result_added',
    'Student result updated',
    coalesce(new.subject,'Subject') || ' result was entered for ' || coalesce(new.student_id,'a student') || '.',
    new.student_id,new.class,new.subject,new.term,new.session,new.id::text
  );

  return new;
end;
$$;

drop trigger if exists pacsa_class_teacher_result_notice on public.results;
create trigger pacsa_class_teacher_result_notice
after insert or update on public.results
for each row execute function public.pacsa_notify_class_teacher_result();

create or replace function public.pacsa_get_my_teacher_notifications(p_limit integer default 20)
returns table(
  id bigint,
  type text,
  title text,
  message text,
  student_id text,
  class text,
  subject text,
  term text,
  session text,
  is_read boolean,
  created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select n.id,n.type,n.title,n.message,n.student_id,n.class,n.subject,n.term,n.session,n.is_read,n.created_at
  from public.teacher_notifications n
  join public."Teachers" t on t.teacher_id=n.teacher_id
  where t.auth_user_id=auth.uid()
    and exists (
      select 1 from public.class_teacher_assignments c
      where c.teacher_id=t.teacher_id
    )
  order by n.created_at desc
  limit greatest(1,least(coalesce(p_limit,20),50));
$$;

create or replace function public.pacsa_mark_my_teacher_notifications_read()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare affected integer;
begin
  update public.teacher_notifications n
  set is_read=true
  where is_read=false
    and n.teacher_id=(select t.teacher_id from public."Teachers" t where t.auth_user_id=auth.uid() limit 1);
  get diagnostics affected = row_count;
  return affected;
end;
$$;

revoke all on function public.pacsa_get_my_teacher_notifications(integer) from public;
revoke all on function public.pacsa_mark_my_teacher_notifications_read() from public;
grant execute on function public.pacsa_get_my_teacher_notifications(integer) to authenticated;
grant execute on function public.pacsa_mark_my_teacher_notifications_read() to authenticated;

-- Restrict privileged role-changing RPCs to authenticated users only.
revoke all on function public.pacsa_superadmin_set_teacher_role(text,text) from public;
revoke all on function public.pacsa_superadmin_set_assessment_stage(text,text,text) from public;
grant execute on function public.pacsa_superadmin_set_teacher_role(text,text) to authenticated;
grant execute on function public.pacsa_superadmin_set_assessment_stage(text,text,text) to authenticated;

commit;
